spring:
  application:
    name: locker-server
  pid:
    file: locker.pid
  h2:
    console:
      enabled: true
  datasource:
    data: classpath:data.sql

server:
  port: 8001

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8000/eureka/
