spring:
  application:
    name: my-eureka
  pid:
    # 将 PID 写入 /var/run 路径下的 myApp.pid 文件中
    file: eureka.pid

server:
  port: 8000

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    serviceUrl:
      defaultZone: http://localhost:8000/eureka/
