spring:
  application:
    name: order-server
  pid:
    file: order.pid
  h2:
    console:
      enabled: true
  datasource:
    data: classpath:data.sql

server:
  port: 8002

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8000/eureka/
feign:
  hystrix:
    enabled: true