spring:
  application:
    name: storage-server
  pid:
    file: storage.pid
  h2:
    console:
      enabled: true
  datasource:
    data: classpath:data.sql

server:
  port: 8003

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8000/eureka/
